// This code is autogenerated. Do not modify manually.
export type Maybe<T> = T;
export type Exact<T extends { [key: string]: unknown }> = {
  [K in keyof T]: T[K];
};
export type MakeOptional<T, K extends keyof T> = Omit<T, K> &
  { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> &
  { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /**
   * A date-time string at UTC, such as 2007-12-03T10:15:30Z,
   *     compliant with the 'date-time' format outlined in section 5.6 of
   *     the RFC 3339 profile of the ISO 8601 standard for representation
   *     of dates and times using the Gregorian calendar.
   */
  DateTime: any;
  /** The 'Dimension' type represents dimensions as whole numeric values between `1` and `4000`. */
  Dimension: any;
  /** The 'HexColor' type represents color in `rgb:ffffff` string format. */
  HexColor: any;
  /** The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). */
  JSON: any;
  /** The 'Quality' type represents quality as whole numeric values between `1` and `100`. */
  Quality: any;
};

/** Represents a binary file in a space. An asset can be any file type. */
export type GraphQLContentfulAsset = {
  __typename?: "Asset";
  sys: GraphQLContentfulSys;
  contentfulMetadata: GraphQLContentfulContentfulMetadata;
  title?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  contentType?: Maybe<Scalars["String"]>;
  fileName?: Maybe<Scalars["String"]>;
  size?: Maybe<Scalars["Int"]>;
  url?: Maybe<Scalars["String"]>;
  width?: Maybe<Scalars["Int"]>;
  height?: Maybe<Scalars["Int"]>;
  linkedFrom?: Maybe<GraphQLContentfulAssetLinkingCollections>;
};

/** Represents a binary file in a space. An asset can be any file type. */
export type GraphQLContentfulAssetUrlArgs = {
  transform?: Maybe<GraphQLContentfulImageTransformOptions>;
};

/** Represents a binary file in a space. An asset can be any file type. */
export type GraphQLContentfulAssetLinkedFromArgs = {
  allowedLocales?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

export type GraphQLContentfulAssetCollection = {
  __typename?: "AssetCollection";
  total: Scalars["Int"];
  skip: Scalars["Int"];
  limit: Scalars["Int"];
  items: Array<Maybe<GraphQLContentfulAsset>>;
};

export type GraphQLContentfulAssetFilter = {
  sys?: Maybe<GraphQLContentfulSysFilter>;
  contentfulMetadata?: Maybe<GraphQLContentfulContentfulMetadataFilter>;
  title_exists?: Maybe<Scalars["Boolean"]>;
  title?: Maybe<Scalars["String"]>;
  title_not?: Maybe<Scalars["String"]>;
  title_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_contains?: Maybe<Scalars["String"]>;
  title_not_contains?: Maybe<Scalars["String"]>;
  description_exists?: Maybe<Scalars["Boolean"]>;
  description?: Maybe<Scalars["String"]>;
  description_not?: Maybe<Scalars["String"]>;
  description_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  description_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  description_contains?: Maybe<Scalars["String"]>;
  description_not_contains?: Maybe<Scalars["String"]>;
  url_exists?: Maybe<Scalars["Boolean"]>;
  url?: Maybe<Scalars["String"]>;
  url_not?: Maybe<Scalars["String"]>;
  url_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  url_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  url_contains?: Maybe<Scalars["String"]>;
  url_not_contains?: Maybe<Scalars["String"]>;
  size_exists?: Maybe<Scalars["Boolean"]>;
  size?: Maybe<Scalars["Int"]>;
  size_not?: Maybe<Scalars["Int"]>;
  size_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  size_not_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  size_gt?: Maybe<Scalars["Int"]>;
  size_gte?: Maybe<Scalars["Int"]>;
  size_lt?: Maybe<Scalars["Int"]>;
  size_lte?: Maybe<Scalars["Int"]>;
  contentType_exists?: Maybe<Scalars["Boolean"]>;
  contentType?: Maybe<Scalars["String"]>;
  contentType_not?: Maybe<Scalars["String"]>;
  contentType_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  contentType_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  contentType_contains?: Maybe<Scalars["String"]>;
  contentType_not_contains?: Maybe<Scalars["String"]>;
  fileName_exists?: Maybe<Scalars["Boolean"]>;
  fileName?: Maybe<Scalars["String"]>;
  fileName_not?: Maybe<Scalars["String"]>;
  fileName_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  fileName_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  fileName_contains?: Maybe<Scalars["String"]>;
  fileName_not_contains?: Maybe<Scalars["String"]>;
  width_exists?: Maybe<Scalars["Boolean"]>;
  width?: Maybe<Scalars["Int"]>;
  width_not?: Maybe<Scalars["Int"]>;
  width_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  width_not_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  width_gt?: Maybe<Scalars["Int"]>;
  width_gte?: Maybe<Scalars["Int"]>;
  width_lt?: Maybe<Scalars["Int"]>;
  width_lte?: Maybe<Scalars["Int"]>;
  height_exists?: Maybe<Scalars["Boolean"]>;
  height?: Maybe<Scalars["Int"]>;
  height_not?: Maybe<Scalars["Int"]>;
  height_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  height_not_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  height_gt?: Maybe<Scalars["Int"]>;
  height_gte?: Maybe<Scalars["Int"]>;
  height_lt?: Maybe<Scalars["Int"]>;
  height_lte?: Maybe<Scalars["Int"]>;
  OR?: Maybe<Array<Maybe<GraphQLContentfulAssetFilter>>>;
  AND?: Maybe<Array<Maybe<GraphQLContentfulAssetFilter>>>;
};

export type GraphQLContentfulAssetLinkingCollections = {
  __typename?: "AssetLinkingCollections";
  entryCollection?: Maybe<GraphQLContentfulEntryCollection>;
  blogPostCollection?: Maybe<GraphQLContentfulBlogPostCollection>;
  landingFactCollection?: Maybe<GraphQLContentfulLandingFactCollection>;
};

export type GraphQLContentfulAssetLinkingCollectionsEntryCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulAssetLinkingCollectionsBlogPostCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulAssetLinkingCollectionsLandingFactCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulAssetOrder =
  | "url_ASC"
  | "url_DESC"
  | "size_ASC"
  | "size_DESC"
  | "contentType_ASC"
  | "contentType_DESC"
  | "fileName_ASC"
  | "fileName_DESC"
  | "width_ASC"
  | "width_DESC"
  | "height_ASC"
  | "height_DESC"
  | "sys_id_ASC"
  | "sys_id_DESC"
  | "sys_publishedAt_ASC"
  | "sys_publishedAt_DESC"
  | "sys_firstPublishedAt_ASC"
  | "sys_firstPublishedAt_DESC"
  | "sys_publishedVersion_ASC"
  | "sys_publishedVersion_DESC";

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/blogPost) */
export type GraphQLContentfulBlogPost = GraphQLContentfulEntry & {
  __typename?: "BlogPost";
  sys: GraphQLContentfulSys;
  contentfulMetadata: GraphQLContentfulContentfulMetadata;
  linkedFrom?: Maybe<GraphQLContentfulBlogPostLinkingCollections>;
  title?: Maybe<Scalars["String"]>;
  image?: Maybe<GraphQLContentfulAsset>;
  path?: Maybe<Scalars["String"]>;
  author?: Maybe<Scalars["String"]>;
  description?: Maybe<GraphQLContentfulBlogPostDescription>;
  tags?: Maybe<Array<Maybe<Scalars["String"]>>>;
  pinned?: Maybe<Scalars["Boolean"]>;
  externalUrl?: Maybe<Scalars["String"]>;
  seoDescription?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/blogPost) */
export type GraphQLContentfulBlogPostLinkedFromArgs = {
  allowedLocales?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/blogPost) */
export type GraphQLContentfulBlogPostTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/blogPost) */
export type GraphQLContentfulBlogPostImageArgs = {
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/blogPost) */
export type GraphQLContentfulBlogPostPathArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/blogPost) */
export type GraphQLContentfulBlogPostAuthorArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/blogPost) */
export type GraphQLContentfulBlogPostDescriptionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/blogPost) */
export type GraphQLContentfulBlogPostTagsArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/blogPost) */
export type GraphQLContentfulBlogPostPinnedArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/blogPost) */
export type GraphQLContentfulBlogPostExternalUrlArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/blogPost) */
export type GraphQLContentfulBlogPostSeoDescriptionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulBlogPostCollection = {
  __typename?: "BlogPostCollection";
  total: Scalars["Int"];
  skip: Scalars["Int"];
  limit: Scalars["Int"];
  items: Array<Maybe<GraphQLContentfulBlogPost>>;
};

export type GraphQLContentfulBlogPostDescription = {
  __typename?: "BlogPostDescription";
  json: Scalars["JSON"];
  links: GraphQLContentfulBlogPostDescriptionLinks;
};

export type GraphQLContentfulBlogPostDescriptionAssets = {
  __typename?: "BlogPostDescriptionAssets";
  hyperlink: Array<Maybe<GraphQLContentfulAsset>>;
  block: Array<Maybe<GraphQLContentfulAsset>>;
};

export type GraphQLContentfulBlogPostDescriptionEntries = {
  __typename?: "BlogPostDescriptionEntries";
  inline: Array<Maybe<GraphQLContentfulEntry>>;
  hyperlink: Array<Maybe<GraphQLContentfulEntry>>;
  block: Array<Maybe<GraphQLContentfulEntry>>;
};

export type GraphQLContentfulBlogPostDescriptionLinks = {
  __typename?: "BlogPostDescriptionLinks";
  entries: GraphQLContentfulBlogPostDescriptionEntries;
  assets: GraphQLContentfulBlogPostDescriptionAssets;
};

export type GraphQLContentfulBlogPostFilter = {
  sys?: Maybe<GraphQLContentfulSysFilter>;
  contentfulMetadata?: Maybe<GraphQLContentfulContentfulMetadataFilter>;
  title_exists?: Maybe<Scalars["Boolean"]>;
  title?: Maybe<Scalars["String"]>;
  title_not?: Maybe<Scalars["String"]>;
  title_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_contains?: Maybe<Scalars["String"]>;
  title_not_contains?: Maybe<Scalars["String"]>;
  image_exists?: Maybe<Scalars["Boolean"]>;
  path_exists?: Maybe<Scalars["Boolean"]>;
  path?: Maybe<Scalars["String"]>;
  path_not?: Maybe<Scalars["String"]>;
  path_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  path_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  path_contains?: Maybe<Scalars["String"]>;
  path_not_contains?: Maybe<Scalars["String"]>;
  author_exists?: Maybe<Scalars["Boolean"]>;
  author?: Maybe<Scalars["String"]>;
  author_not?: Maybe<Scalars["String"]>;
  author_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  author_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  author_contains?: Maybe<Scalars["String"]>;
  author_not_contains?: Maybe<Scalars["String"]>;
  description_exists?: Maybe<Scalars["Boolean"]>;
  description_contains?: Maybe<Scalars["String"]>;
  description_not_contains?: Maybe<Scalars["String"]>;
  tags_exists?: Maybe<Scalars["Boolean"]>;
  tags_contains_all?: Maybe<Array<Maybe<Scalars["String"]>>>;
  tags_contains_some?: Maybe<Array<Maybe<Scalars["String"]>>>;
  tags_contains_none?: Maybe<Array<Maybe<Scalars["String"]>>>;
  pinned_exists?: Maybe<Scalars["Boolean"]>;
  pinned?: Maybe<Scalars["Boolean"]>;
  pinned_not?: Maybe<Scalars["Boolean"]>;
  externalUrl_exists?: Maybe<Scalars["Boolean"]>;
  externalUrl?: Maybe<Scalars["String"]>;
  externalUrl_not?: Maybe<Scalars["String"]>;
  externalUrl_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  externalUrl_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  externalUrl_contains?: Maybe<Scalars["String"]>;
  externalUrl_not_contains?: Maybe<Scalars["String"]>;
  seoDescription_exists?: Maybe<Scalars["Boolean"]>;
  seoDescription?: Maybe<Scalars["String"]>;
  seoDescription_not?: Maybe<Scalars["String"]>;
  seoDescription_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  seoDescription_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  seoDescription_contains?: Maybe<Scalars["String"]>;
  seoDescription_not_contains?: Maybe<Scalars["String"]>;
  OR?: Maybe<Array<Maybe<GraphQLContentfulBlogPostFilter>>>;
  AND?: Maybe<Array<Maybe<GraphQLContentfulBlogPostFilter>>>;
};

export type GraphQLContentfulBlogPostLinkingCollections = {
  __typename?: "BlogPostLinkingCollections";
  entryCollection?: Maybe<GraphQLContentfulEntryCollection>;
};

export type GraphQLContentfulBlogPostLinkingCollectionsEntryCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulBlogPostOrder =
  | "title_ASC"
  | "title_DESC"
  | "path_ASC"
  | "path_DESC"
  | "author_ASC"
  | "author_DESC"
  | "pinned_ASC"
  | "pinned_DESC"
  | "externalUrl_ASC"
  | "externalUrl_DESC"
  | "sys_id_ASC"
  | "sys_id_DESC"
  | "sys_publishedAt_ASC"
  | "sys_publishedAt_DESC"
  | "sys_firstPublishedAt_ASC"
  | "sys_firstPublishedAt_DESC"
  | "sys_publishedVersion_ASC"
  | "sys_publishedVersion_DESC";

export type GraphQLContentfulContentfulMetadata = {
  __typename?: "ContentfulMetadata";
  tags: Array<Maybe<GraphQLContentfulContentfulTag>>;
};

export type GraphQLContentfulContentfulMetadataFilter = {
  tags_exists?: Maybe<Scalars["Boolean"]>;
  tags?: Maybe<GraphQLContentfulContentfulMetadataTagsFilter>;
};

export type GraphQLContentfulContentfulMetadataTagsFilter = {
  id_contains_all?: Maybe<Array<Maybe<Scalars["String"]>>>;
  id_contains_some?: Maybe<Array<Maybe<Scalars["String"]>>>;
  id_contains_none?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

/**
 * Represents a tag entity for finding and organizing content easily.
 *     Find out more here: https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/content-tags
 */
export type GraphQLContentfulContentfulTag = {
  __typename?: "ContentfulTag";
  id?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/didYouKnow) */
export type GraphQLContentfulDidYouKnow = GraphQLContentfulEntry & {
  __typename?: "DidYouKnow";
  sys: GraphQLContentfulSys;
  contentfulMetadata: GraphQLContentfulContentfulMetadata;
  linkedFrom?: Maybe<GraphQLContentfulDidYouKnowLinkingCollections>;
  title?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  sourceName?: Maybe<Scalars["String"]>;
  sourceUrl?: Maybe<Scalars["String"]>;
  order?: Maybe<Scalars["Int"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/didYouKnow) */
export type GraphQLContentfulDidYouKnowLinkedFromArgs = {
  allowedLocales?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/didYouKnow) */
export type GraphQLContentfulDidYouKnowTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/didYouKnow) */
export type GraphQLContentfulDidYouKnowDescriptionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/didYouKnow) */
export type GraphQLContentfulDidYouKnowSourceNameArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/didYouKnow) */
export type GraphQLContentfulDidYouKnowSourceUrlArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/didYouKnow) */
export type GraphQLContentfulDidYouKnowOrderArgs = {
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulDidYouKnowCollection = {
  __typename?: "DidYouKnowCollection";
  total: Scalars["Int"];
  skip: Scalars["Int"];
  limit: Scalars["Int"];
  items: Array<Maybe<GraphQLContentfulDidYouKnow>>;
};

export type GraphQLContentfulDidYouKnowFilter = {
  sys?: Maybe<GraphQLContentfulSysFilter>;
  contentfulMetadata?: Maybe<GraphQLContentfulContentfulMetadataFilter>;
  title_exists?: Maybe<Scalars["Boolean"]>;
  title?: Maybe<Scalars["String"]>;
  title_not?: Maybe<Scalars["String"]>;
  title_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_contains?: Maybe<Scalars["String"]>;
  title_not_contains?: Maybe<Scalars["String"]>;
  description_exists?: Maybe<Scalars["Boolean"]>;
  description?: Maybe<Scalars["String"]>;
  description_not?: Maybe<Scalars["String"]>;
  description_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  description_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  description_contains?: Maybe<Scalars["String"]>;
  description_not_contains?: Maybe<Scalars["String"]>;
  sourceName_exists?: Maybe<Scalars["Boolean"]>;
  sourceName?: Maybe<Scalars["String"]>;
  sourceName_not?: Maybe<Scalars["String"]>;
  sourceName_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  sourceName_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  sourceName_contains?: Maybe<Scalars["String"]>;
  sourceName_not_contains?: Maybe<Scalars["String"]>;
  sourceUrl_exists?: Maybe<Scalars["Boolean"]>;
  sourceUrl?: Maybe<Scalars["String"]>;
  sourceUrl_not?: Maybe<Scalars["String"]>;
  sourceUrl_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  sourceUrl_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  sourceUrl_contains?: Maybe<Scalars["String"]>;
  sourceUrl_not_contains?: Maybe<Scalars["String"]>;
  order_exists?: Maybe<Scalars["Boolean"]>;
  order?: Maybe<Scalars["Int"]>;
  order_not?: Maybe<Scalars["Int"]>;
  order_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_not_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_gt?: Maybe<Scalars["Int"]>;
  order_gte?: Maybe<Scalars["Int"]>;
  order_lt?: Maybe<Scalars["Int"]>;
  order_lte?: Maybe<Scalars["Int"]>;
  OR?: Maybe<Array<Maybe<GraphQLContentfulDidYouKnowFilter>>>;
  AND?: Maybe<Array<Maybe<GraphQLContentfulDidYouKnowFilter>>>;
};

export type GraphQLContentfulDidYouKnowLinkingCollections = {
  __typename?: "DidYouKnowLinkingCollections";
  entryCollection?: Maybe<GraphQLContentfulEntryCollection>;
};

export type GraphQLContentfulDidYouKnowLinkingCollectionsEntryCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulDidYouKnowOrder =
  | "title_ASC"
  | "title_DESC"
  | "sourceName_ASC"
  | "sourceName_DESC"
  | "sourceUrl_ASC"
  | "sourceUrl_DESC"
  | "order_ASC"
  | "order_DESC"
  | "sys_id_ASC"
  | "sys_id_DESC"
  | "sys_publishedAt_ASC"
  | "sys_publishedAt_DESC"
  | "sys_firstPublishedAt_ASC"
  | "sys_firstPublishedAt_DESC"
  | "sys_publishedVersion_ASC"
  | "sys_publishedVersion_DESC";

export type GraphQLContentfulEntry = {
  sys: GraphQLContentfulSys;
  contentfulMetadata: GraphQLContentfulContentfulMetadata;
};

export type GraphQLContentfulEntryCollection = {
  __typename?: "EntryCollection";
  total: Scalars["Int"];
  skip: Scalars["Int"];
  limit: Scalars["Int"];
  items: Array<Maybe<GraphQLContentfulEntry>>;
};

export type GraphQLContentfulEntryFilter = {
  sys?: Maybe<GraphQLContentfulSysFilter>;
  contentfulMetadata?: Maybe<GraphQLContentfulContentfulMetadataFilter>;
  OR?: Maybe<Array<Maybe<GraphQLContentfulEntryFilter>>>;
  AND?: Maybe<Array<Maybe<GraphQLContentfulEntryFilter>>>;
};

export type GraphQLContentfulEntryOrder =
  | "sys_id_ASC"
  | "sys_id_DESC"
  | "sys_publishedAt_ASC"
  | "sys_publishedAt_DESC"
  | "sys_firstPublishedAt_ASC"
  | "sys_firstPublishedAt_DESC"
  | "sys_publishedVersion_ASC"
  | "sys_publishedVersion_DESC";

export type GraphQLContentfulImageFormat =
  /** JPG image format. */
  | "JPG"
  /**
   * Progressive JPG format stores multiple passes of an image in progressively higher detail.
   *         When a progressive image is loading, the viewer will first see a lower quality pixelated version which
   *         will gradually improve in detail, until the image is fully downloaded. This is to display an image as
   *         early as possible to make the layout look as designed.
   */
  | "JPG_PROGRESSIVE"
  /** PNG image format */
  | "PNG"
  /**
   * 8-bit PNG images support up to 256 colors and weigh less than the standard 24-bit PNG equivalent.
   *         The 8-bit PNG format is mostly used for simple images, such as icons or logos.
   */
  | "PNG8"
  /** WebP image format. */
  | "WEBP";

export type GraphQLContentfulImageResizeFocus =
  /** Focus the resizing on the center. */
  | "CENTER"
  /** Focus the resizing on the top. */
  | "TOP"
  /** Focus the resizing on the top right. */
  | "TOP_RIGHT"
  /** Focus the resizing on the right. */
  | "RIGHT"
  /** Focus the resizing on the bottom right. */
  | "BOTTOM_RIGHT"
  /** Focus the resizing on the bottom. */
  | "BOTTOM"
  /** Focus the resizing on the bottom left. */
  | "BOTTOM_LEFT"
  /** Focus the resizing on the left. */
  | "LEFT"
  /** Focus the resizing on the top left. */
  | "TOP_LEFT"
  /** Focus the resizing on the largest face. */
  | "FACE"
  /** Focus the resizing on the area containing all the faces. */
  | "FACES";

export type GraphQLContentfulImageResizeStrategy =
  /** Resizes the image to fit into the specified dimensions. */
  | "FIT"
  /**
   * Resizes the image to the specified dimensions, padding the image if needed.
   *         Uses desired background color as padding color.
   */
  | "PAD"
  /** Resizes the image to the specified dimensions, cropping the image if needed. */
  | "FILL"
  /** Resizes the image to the specified dimensions, changing the original aspect ratio if needed. */
  | "SCALE"
  /** Crops a part of the original image to fit into the specified dimensions. */
  | "CROP"
  /** Creates a thumbnail from the image. */
  | "THUMB";

export type GraphQLContentfulImageTransformOptions = {
  /** Desired width in pixels. Defaults to the original image width. */
  width?: Maybe<Scalars["Dimension"]>;
  /** Desired height in pixels. Defaults to the original image height. */
  height?: Maybe<Scalars["Dimension"]>;
  /**
   * Desired quality of the image in percents.
   *         Used for `PNG8`, `JPG`, `JPG_PROGRESSIVE` and `WEBP` formats.
   */
  quality?: Maybe<Scalars["Quality"]>;
  /**
   * Desired corner radius in pixels.
   *         Results in an image with rounded corners (pass `-1` for a full circle/ellipse).
   *         Defaults to `0`. Uses desired background color as padding color,
   *         unless the format is `JPG` or `JPG_PROGRESSIVE` and resize strategy is `PAD`, then defaults to white.
   */
  cornerRadius?: Maybe<Scalars["Int"]>;
  /** Desired resize strategy. Defaults to `FIT`. */
  resizeStrategy?: Maybe<GraphQLContentfulImageResizeStrategy>;
  /** Desired resize focus area. Defaults to `CENTER`. */
  resizeFocus?: Maybe<GraphQLContentfulImageResizeFocus>;
  /**
   * Desired background color, used with corner radius or `PAD` resize strategy.
   *         Defaults to transparent (for `PNG`, `PNG8` and `WEBP`) or white (for `JPG` and `JPG_PROGRESSIVE`).
   */
  backgroundColor?: Maybe<Scalars["HexColor"]>;
  /** Desired image format. Defaults to the original image format. */
  format?: Maybe<GraphQLContentfulImageFormat>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingExplanation) */
export type GraphQLContentfulLandingExplanation = GraphQLContentfulEntry & {
  __typename?: "LandingExplanation";
  sys: GraphQLContentfulSys;
  contentfulMetadata: GraphQLContentfulContentfulMetadata;
  linkedFrom?: Maybe<GraphQLContentfulLandingExplanationLinkingCollections>;
  title?: Maybe<Scalars["String"]>;
  icon?: Maybe<Scalars["String"]>;
  description?: Maybe<GraphQLContentfulLandingExplanationDescription>;
  order?: Maybe<Scalars["Int"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingExplanation) */
export type GraphQLContentfulLandingExplanationLinkedFromArgs = {
  allowedLocales?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingExplanation) */
export type GraphQLContentfulLandingExplanationTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingExplanation) */
export type GraphQLContentfulLandingExplanationIconArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingExplanation) */
export type GraphQLContentfulLandingExplanationDescriptionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingExplanation) */
export type GraphQLContentfulLandingExplanationOrderArgs = {
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulLandingExplanationCollection = {
  __typename?: "LandingExplanationCollection";
  total: Scalars["Int"];
  skip: Scalars["Int"];
  limit: Scalars["Int"];
  items: Array<Maybe<GraphQLContentfulLandingExplanation>>;
};

export type GraphQLContentfulLandingExplanationDescription = {
  __typename?: "LandingExplanationDescription";
  json: Scalars["JSON"];
  links: GraphQLContentfulLandingExplanationDescriptionLinks;
};

export type GraphQLContentfulLandingExplanationDescriptionAssets = {
  __typename?: "LandingExplanationDescriptionAssets";
  hyperlink: Array<Maybe<GraphQLContentfulAsset>>;
  block: Array<Maybe<GraphQLContentfulAsset>>;
};

export type GraphQLContentfulLandingExplanationDescriptionEntries = {
  __typename?: "LandingExplanationDescriptionEntries";
  inline: Array<Maybe<GraphQLContentfulEntry>>;
  hyperlink: Array<Maybe<GraphQLContentfulEntry>>;
  block: Array<Maybe<GraphQLContentfulEntry>>;
};

export type GraphQLContentfulLandingExplanationDescriptionLinks = {
  __typename?: "LandingExplanationDescriptionLinks";
  entries: GraphQLContentfulLandingExplanationDescriptionEntries;
  assets: GraphQLContentfulLandingExplanationDescriptionAssets;
};

export type GraphQLContentfulLandingExplanationFilter = {
  sys?: Maybe<GraphQLContentfulSysFilter>;
  contentfulMetadata?: Maybe<GraphQLContentfulContentfulMetadataFilter>;
  title_exists?: Maybe<Scalars["Boolean"]>;
  title?: Maybe<Scalars["String"]>;
  title_not?: Maybe<Scalars["String"]>;
  title_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_contains?: Maybe<Scalars["String"]>;
  title_not_contains?: Maybe<Scalars["String"]>;
  icon_exists?: Maybe<Scalars["Boolean"]>;
  icon?: Maybe<Scalars["String"]>;
  icon_not?: Maybe<Scalars["String"]>;
  icon_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  icon_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  icon_contains?: Maybe<Scalars["String"]>;
  icon_not_contains?: Maybe<Scalars["String"]>;
  description_exists?: Maybe<Scalars["Boolean"]>;
  description_contains?: Maybe<Scalars["String"]>;
  description_not_contains?: Maybe<Scalars["String"]>;
  order_exists?: Maybe<Scalars["Boolean"]>;
  order?: Maybe<Scalars["Int"]>;
  order_not?: Maybe<Scalars["Int"]>;
  order_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_not_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_gt?: Maybe<Scalars["Int"]>;
  order_gte?: Maybe<Scalars["Int"]>;
  order_lt?: Maybe<Scalars["Int"]>;
  order_lte?: Maybe<Scalars["Int"]>;
  OR?: Maybe<Array<Maybe<GraphQLContentfulLandingExplanationFilter>>>;
  AND?: Maybe<Array<Maybe<GraphQLContentfulLandingExplanationFilter>>>;
};

export type GraphQLContentfulLandingExplanationLinkingCollections = {
  __typename?: "LandingExplanationLinkingCollections";
  entryCollection?: Maybe<GraphQLContentfulEntryCollection>;
};

export type GraphQLContentfulLandingExplanationLinkingCollectionsEntryCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulLandingExplanationOrder =
  | "title_ASC"
  | "title_DESC"
  | "icon_ASC"
  | "icon_DESC"
  | "order_ASC"
  | "order_DESC"
  | "sys_id_ASC"
  | "sys_id_DESC"
  | "sys_publishedAt_ASC"
  | "sys_publishedAt_DESC"
  | "sys_firstPublishedAt_ASC"
  | "sys_firstPublishedAt_DESC"
  | "sys_publishedVersion_ASC"
  | "sys_publishedVersion_DESC";

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingFact) */
export type GraphQLContentfulLandingFact = GraphQLContentfulEntry & {
  __typename?: "LandingFact";
  sys: GraphQLContentfulSys;
  contentfulMetadata: GraphQLContentfulContentfulMetadata;
  linkedFrom?: Maybe<GraphQLContentfulLandingFactLinkingCollections>;
  title?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  backgroundImage?: Maybe<GraphQLContentfulAsset>;
  order?: Maybe<Scalars["Int"]>;
  lightTextColor?: Maybe<Scalars["Boolean"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingFact) */
export type GraphQLContentfulLandingFactLinkedFromArgs = {
  allowedLocales?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingFact) */
export type GraphQLContentfulLandingFactTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingFact) */
export type GraphQLContentfulLandingFactDescriptionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingFact) */
export type GraphQLContentfulLandingFactBackgroundImageArgs = {
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingFact) */
export type GraphQLContentfulLandingFactOrderArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingFact) */
export type GraphQLContentfulLandingFactLightTextColorArgs = {
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulLandingFactCollection = {
  __typename?: "LandingFactCollection";
  total: Scalars["Int"];
  skip: Scalars["Int"];
  limit: Scalars["Int"];
  items: Array<Maybe<GraphQLContentfulLandingFact>>;
};

export type GraphQLContentfulLandingFactFilter = {
  sys?: Maybe<GraphQLContentfulSysFilter>;
  contentfulMetadata?: Maybe<GraphQLContentfulContentfulMetadataFilter>;
  title_exists?: Maybe<Scalars["Boolean"]>;
  title?: Maybe<Scalars["String"]>;
  title_not?: Maybe<Scalars["String"]>;
  title_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_contains?: Maybe<Scalars["String"]>;
  title_not_contains?: Maybe<Scalars["String"]>;
  description_exists?: Maybe<Scalars["Boolean"]>;
  description?: Maybe<Scalars["String"]>;
  description_not?: Maybe<Scalars["String"]>;
  description_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  description_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  description_contains?: Maybe<Scalars["String"]>;
  description_not_contains?: Maybe<Scalars["String"]>;
  backgroundImage_exists?: Maybe<Scalars["Boolean"]>;
  order_exists?: Maybe<Scalars["Boolean"]>;
  order?: Maybe<Scalars["Int"]>;
  order_not?: Maybe<Scalars["Int"]>;
  order_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_not_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_gt?: Maybe<Scalars["Int"]>;
  order_gte?: Maybe<Scalars["Int"]>;
  order_lt?: Maybe<Scalars["Int"]>;
  order_lte?: Maybe<Scalars["Int"]>;
  lightTextColor_exists?: Maybe<Scalars["Boolean"]>;
  lightTextColor?: Maybe<Scalars["Boolean"]>;
  lightTextColor_not?: Maybe<Scalars["Boolean"]>;
  OR?: Maybe<Array<Maybe<GraphQLContentfulLandingFactFilter>>>;
  AND?: Maybe<Array<Maybe<GraphQLContentfulLandingFactFilter>>>;
};

export type GraphQLContentfulLandingFactLinkingCollections = {
  __typename?: "LandingFactLinkingCollections";
  entryCollection?: Maybe<GraphQLContentfulEntryCollection>;
};

export type GraphQLContentfulLandingFactLinkingCollectionsEntryCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulLandingFactOrder =
  | "title_ASC"
  | "title_DESC"
  | "description_ASC"
  | "description_DESC"
  | "order_ASC"
  | "order_DESC"
  | "lightTextColor_ASC"
  | "lightTextColor_DESC"
  | "sys_id_ASC"
  | "sys_id_DESC"
  | "sys_publishedAt_ASC"
  | "sys_publishedAt_DESC"
  | "sys_firstPublishedAt_ASC"
  | "sys_firstPublishedAt_DESC"
  | "sys_publishedVersion_ASC"
  | "sys_publishedVersion_DESC";

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingMetadata) */
export type GraphQLContentfulLandingMetadata = GraphQLContentfulEntry & {
  __typename?: "LandingMetadata";
  sys: GraphQLContentfulSys;
  contentfulMetadata: GraphQLContentfulContentfulMetadata;
  linkedFrom?: Maybe<GraphQLContentfulLandingMetadataLinkingCollections>;
  title?: Maybe<Scalars["String"]>;
  description?: Maybe<GraphQLContentfulLandingMetadataDescription>;
  buttonStartNow?: Maybe<Scalars["String"]>;
  whyThisToolTitle?: Maybe<Scalars["String"]>;
  howWeHelpTitle?: Maybe<Scalars["String"]>;
  kitchenIntro?: Maybe<Scalars["String"]>;
  didYouKnowTitle?: Maybe<Scalars["String"]>;
  articleTitle?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingMetadata) */
export type GraphQLContentfulLandingMetadataLinkedFromArgs = {
  allowedLocales?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingMetadata) */
export type GraphQLContentfulLandingMetadataTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingMetadata) */
export type GraphQLContentfulLandingMetadataDescriptionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingMetadata) */
export type GraphQLContentfulLandingMetadataButtonStartNowArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingMetadata) */
export type GraphQLContentfulLandingMetadataWhyThisToolTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingMetadata) */
export type GraphQLContentfulLandingMetadataHowWeHelpTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingMetadata) */
export type GraphQLContentfulLandingMetadataKitchenIntroArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingMetadata) */
export type GraphQLContentfulLandingMetadataDidYouKnowTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/landingMetadata) */
export type GraphQLContentfulLandingMetadataArticleTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulLandingMetadataCollection = {
  __typename?: "LandingMetadataCollection";
  total: Scalars["Int"];
  skip: Scalars["Int"];
  limit: Scalars["Int"];
  items: Array<Maybe<GraphQLContentfulLandingMetadata>>;
};

export type GraphQLContentfulLandingMetadataDescription = {
  __typename?: "LandingMetadataDescription";
  json: Scalars["JSON"];
  links: GraphQLContentfulLandingMetadataDescriptionLinks;
};

export type GraphQLContentfulLandingMetadataDescriptionAssets = {
  __typename?: "LandingMetadataDescriptionAssets";
  hyperlink: Array<Maybe<GraphQLContentfulAsset>>;
  block: Array<Maybe<GraphQLContentfulAsset>>;
};

export type GraphQLContentfulLandingMetadataDescriptionEntries = {
  __typename?: "LandingMetadataDescriptionEntries";
  inline: Array<Maybe<GraphQLContentfulEntry>>;
  hyperlink: Array<Maybe<GraphQLContentfulEntry>>;
  block: Array<Maybe<GraphQLContentfulEntry>>;
};

export type GraphQLContentfulLandingMetadataDescriptionLinks = {
  __typename?: "LandingMetadataDescriptionLinks";
  entries: GraphQLContentfulLandingMetadataDescriptionEntries;
  assets: GraphQLContentfulLandingMetadataDescriptionAssets;
};

export type GraphQLContentfulLandingMetadataFilter = {
  sys?: Maybe<GraphQLContentfulSysFilter>;
  contentfulMetadata?: Maybe<GraphQLContentfulContentfulMetadataFilter>;
  title_exists?: Maybe<Scalars["Boolean"]>;
  title?: Maybe<Scalars["String"]>;
  title_not?: Maybe<Scalars["String"]>;
  title_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_contains?: Maybe<Scalars["String"]>;
  title_not_contains?: Maybe<Scalars["String"]>;
  description_exists?: Maybe<Scalars["Boolean"]>;
  description_contains?: Maybe<Scalars["String"]>;
  description_not_contains?: Maybe<Scalars["String"]>;
  buttonStartNow_exists?: Maybe<Scalars["Boolean"]>;
  buttonStartNow?: Maybe<Scalars["String"]>;
  buttonStartNow_not?: Maybe<Scalars["String"]>;
  buttonStartNow_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  buttonStartNow_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  buttonStartNow_contains?: Maybe<Scalars["String"]>;
  buttonStartNow_not_contains?: Maybe<Scalars["String"]>;
  whyThisToolTitle_exists?: Maybe<Scalars["Boolean"]>;
  whyThisToolTitle?: Maybe<Scalars["String"]>;
  whyThisToolTitle_not?: Maybe<Scalars["String"]>;
  whyThisToolTitle_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  whyThisToolTitle_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  whyThisToolTitle_contains?: Maybe<Scalars["String"]>;
  whyThisToolTitle_not_contains?: Maybe<Scalars["String"]>;
  howWeHelpTitle_exists?: Maybe<Scalars["Boolean"]>;
  howWeHelpTitle?: Maybe<Scalars["String"]>;
  howWeHelpTitle_not?: Maybe<Scalars["String"]>;
  howWeHelpTitle_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  howWeHelpTitle_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  howWeHelpTitle_contains?: Maybe<Scalars["String"]>;
  howWeHelpTitle_not_contains?: Maybe<Scalars["String"]>;
  kitchenIntro_exists?: Maybe<Scalars["Boolean"]>;
  kitchenIntro?: Maybe<Scalars["String"]>;
  kitchenIntro_not?: Maybe<Scalars["String"]>;
  kitchenIntro_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  kitchenIntro_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  kitchenIntro_contains?: Maybe<Scalars["String"]>;
  kitchenIntro_not_contains?: Maybe<Scalars["String"]>;
  didYouKnowTitle_exists?: Maybe<Scalars["Boolean"]>;
  didYouKnowTitle?: Maybe<Scalars["String"]>;
  didYouKnowTitle_not?: Maybe<Scalars["String"]>;
  didYouKnowTitle_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  didYouKnowTitle_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  didYouKnowTitle_contains?: Maybe<Scalars["String"]>;
  didYouKnowTitle_not_contains?: Maybe<Scalars["String"]>;
  articleTitle_exists?: Maybe<Scalars["Boolean"]>;
  articleTitle?: Maybe<Scalars["String"]>;
  articleTitle_not?: Maybe<Scalars["String"]>;
  articleTitle_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  articleTitle_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  articleTitle_contains?: Maybe<Scalars["String"]>;
  articleTitle_not_contains?: Maybe<Scalars["String"]>;
  OR?: Maybe<Array<Maybe<GraphQLContentfulLandingMetadataFilter>>>;
  AND?: Maybe<Array<Maybe<GraphQLContentfulLandingMetadataFilter>>>;
};

export type GraphQLContentfulLandingMetadataLinkingCollections = {
  __typename?: "LandingMetadataLinkingCollections";
  entryCollection?: Maybe<GraphQLContentfulEntryCollection>;
};

export type GraphQLContentfulLandingMetadataLinkingCollectionsEntryCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulLandingMetadataOrder =
  | "title_ASC"
  | "title_DESC"
  | "buttonStartNow_ASC"
  | "buttonStartNow_DESC"
  | "whyThisToolTitle_ASC"
  | "whyThisToolTitle_DESC"
  | "howWeHelpTitle_ASC"
  | "howWeHelpTitle_DESC"
  | "didYouKnowTitle_ASC"
  | "didYouKnowTitle_DESC"
  | "articleTitle_ASC"
  | "articleTitle_DESC"
  | "sys_id_ASC"
  | "sys_id_DESC"
  | "sys_publishedAt_ASC"
  | "sys_publishedAt_DESC"
  | "sys_firstPublishedAt_ASC"
  | "sys_firstPublishedAt_DESC"
  | "sys_publishedVersion_ASC"
  | "sys_publishedVersion_DESC";

/** Example violation for the how we help section [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/offeringExampleViolation) */
export type GraphQLContentfulOfferingExampleViolation = GraphQLContentfulEntry & {
  __typename?: "OfferingExampleViolation";
  sys: GraphQLContentfulSys;
  contentfulMetadata: GraphQLContentfulContentfulMetadata;
  linkedFrom?: Maybe<
    GraphQLContentfulOfferingExampleViolationLinkingCollections
  >;
  title?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  violationReason?: Maybe<Scalars["String"]>;
  order?: Maybe<Scalars["Int"]>;
  markerTopPosition?: Maybe<Scalars["Float"]>;
  markerLeftPosition?: Maybe<Scalars["Float"]>;
};

/** Example violation for the how we help section [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/offeringExampleViolation) */
export type GraphQLContentfulOfferingExampleViolationLinkedFromArgs = {
  allowedLocales?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

/** Example violation for the how we help section [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/offeringExampleViolation) */
export type GraphQLContentfulOfferingExampleViolationTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** Example violation for the how we help section [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/offeringExampleViolation) */
export type GraphQLContentfulOfferingExampleViolationDescriptionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** Example violation for the how we help section [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/offeringExampleViolation) */
export type GraphQLContentfulOfferingExampleViolationViolationReasonArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** Example violation for the how we help section [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/offeringExampleViolation) */
export type GraphQLContentfulOfferingExampleViolationOrderArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** Example violation for the how we help section [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/offeringExampleViolation) */
export type GraphQLContentfulOfferingExampleViolationMarkerTopPositionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** Example violation for the how we help section [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/offeringExampleViolation) */
export type GraphQLContentfulOfferingExampleViolationMarkerLeftPositionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulOfferingExampleViolationCollection = {
  __typename?: "OfferingExampleViolationCollection";
  total: Scalars["Int"];
  skip: Scalars["Int"];
  limit: Scalars["Int"];
  items: Array<Maybe<GraphQLContentfulOfferingExampleViolation>>;
};

export type GraphQLContentfulOfferingExampleViolationFilter = {
  sys?: Maybe<GraphQLContentfulSysFilter>;
  contentfulMetadata?: Maybe<GraphQLContentfulContentfulMetadataFilter>;
  title_exists?: Maybe<Scalars["Boolean"]>;
  title?: Maybe<Scalars["String"]>;
  title_not?: Maybe<Scalars["String"]>;
  title_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_contains?: Maybe<Scalars["String"]>;
  title_not_contains?: Maybe<Scalars["String"]>;
  description_exists?: Maybe<Scalars["Boolean"]>;
  description?: Maybe<Scalars["String"]>;
  description_not?: Maybe<Scalars["String"]>;
  description_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  description_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  description_contains?: Maybe<Scalars["String"]>;
  description_not_contains?: Maybe<Scalars["String"]>;
  violationReason_exists?: Maybe<Scalars["Boolean"]>;
  violationReason?: Maybe<Scalars["String"]>;
  violationReason_not?: Maybe<Scalars["String"]>;
  violationReason_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  violationReason_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  violationReason_contains?: Maybe<Scalars["String"]>;
  violationReason_not_contains?: Maybe<Scalars["String"]>;
  order_exists?: Maybe<Scalars["Boolean"]>;
  order?: Maybe<Scalars["Int"]>;
  order_not?: Maybe<Scalars["Int"]>;
  order_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_not_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_gt?: Maybe<Scalars["Int"]>;
  order_gte?: Maybe<Scalars["Int"]>;
  order_lt?: Maybe<Scalars["Int"]>;
  order_lte?: Maybe<Scalars["Int"]>;
  markerTopPosition_exists?: Maybe<Scalars["Boolean"]>;
  markerTopPosition?: Maybe<Scalars["Float"]>;
  markerTopPosition_not?: Maybe<Scalars["Float"]>;
  markerTopPosition_in?: Maybe<Array<Maybe<Scalars["Float"]>>>;
  markerTopPosition_not_in?: Maybe<Array<Maybe<Scalars["Float"]>>>;
  markerTopPosition_gt?: Maybe<Scalars["Float"]>;
  markerTopPosition_gte?: Maybe<Scalars["Float"]>;
  markerTopPosition_lt?: Maybe<Scalars["Float"]>;
  markerTopPosition_lte?: Maybe<Scalars["Float"]>;
  markerLeftPosition_exists?: Maybe<Scalars["Boolean"]>;
  markerLeftPosition?: Maybe<Scalars["Float"]>;
  markerLeftPosition_not?: Maybe<Scalars["Float"]>;
  markerLeftPosition_in?: Maybe<Array<Maybe<Scalars["Float"]>>>;
  markerLeftPosition_not_in?: Maybe<Array<Maybe<Scalars["Float"]>>>;
  markerLeftPosition_gt?: Maybe<Scalars["Float"]>;
  markerLeftPosition_gte?: Maybe<Scalars["Float"]>;
  markerLeftPosition_lt?: Maybe<Scalars["Float"]>;
  markerLeftPosition_lte?: Maybe<Scalars["Float"]>;
  OR?: Maybe<Array<Maybe<GraphQLContentfulOfferingExampleViolationFilter>>>;
  AND?: Maybe<Array<Maybe<GraphQLContentfulOfferingExampleViolationFilter>>>;
};

export type GraphQLContentfulOfferingExampleViolationLinkingCollections = {
  __typename?: "OfferingExampleViolationLinkingCollections";
  entryCollection?: Maybe<GraphQLContentfulEntryCollection>;
};

export type GraphQLContentfulOfferingExampleViolationLinkingCollectionsEntryCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulOfferingExampleViolationOrder =
  | "title_ASC"
  | "title_DESC"
  | "violationReason_ASC"
  | "violationReason_DESC"
  | "order_ASC"
  | "order_DESC"
  | "markerTopPosition_ASC"
  | "markerTopPosition_DESC"
  | "markerLeftPosition_ASC"
  | "markerLeftPosition_DESC"
  | "sys_id_ASC"
  | "sys_id_DESC"
  | "sys_publishedAt_ASC"
  | "sys_publishedAt_DESC"
  | "sys_firstPublishedAt_ASC"
  | "sys_firstPublishedAt_DESC"
  | "sys_publishedVersion_ASC"
  | "sys_publishedVersion_DESC";

export type GraphQLContentfulQuery = {
  __typename?: "Query";
  asset?: Maybe<GraphQLContentfulAsset>;
  assetCollection?: Maybe<GraphQLContentfulAssetCollection>;
  blogPost?: Maybe<GraphQLContentfulBlogPost>;
  blogPostCollection?: Maybe<GraphQLContentfulBlogPostCollection>;
  richTextOnly?: Maybe<GraphQLContentfulRichTextOnly>;
  richTextOnlyCollection?: Maybe<GraphQLContentfulRichTextOnlyCollection>;
  resourcesAndContacts?: Maybe<GraphQLContentfulResourcesAndContacts>;
  resourcesAndContactsCollection?: Maybe<
    GraphQLContentfulResourcesAndContactsCollection
  >;
  offeringExampleViolation?: Maybe<GraphQLContentfulOfferingExampleViolation>;
  offeringExampleViolationCollection?: Maybe<
    GraphQLContentfulOfferingExampleViolationCollection
  >;
  landingFact?: Maybe<GraphQLContentfulLandingFact>;
  landingFactCollection?: Maybe<GraphQLContentfulLandingFactCollection>;
  landingMetadata?: Maybe<GraphQLContentfulLandingMetadata>;
  landingMetadataCollection?: Maybe<GraphQLContentfulLandingMetadataCollection>;
  relevantArticle?: Maybe<GraphQLContentfulRelevantArticle>;
  relevantArticleCollection?: Maybe<GraphQLContentfulRelevantArticleCollection>;
  didYouKnow?: Maybe<GraphQLContentfulDidYouKnow>;
  didYouKnowCollection?: Maybe<GraphQLContentfulDidYouKnowCollection>;
  landingExplanation?: Maybe<GraphQLContentfulLandingExplanation>;
  landingExplanationCollection?: Maybe<
    GraphQLContentfulLandingExplanationCollection
  >;
  entryCollection?: Maybe<GraphQLContentfulEntryCollection>;
};

export type GraphQLContentfulQueryAssetArgs = {
  id: Scalars["String"];
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulQueryAssetCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
  where?: Maybe<GraphQLContentfulAssetFilter>;
  order?: Maybe<Array<Maybe<GraphQLContentfulAssetOrder>>>;
};

export type GraphQLContentfulQueryBlogPostArgs = {
  id: Scalars["String"];
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulQueryBlogPostCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
  where?: Maybe<GraphQLContentfulBlogPostFilter>;
  order?: Maybe<Array<Maybe<GraphQLContentfulBlogPostOrder>>>;
};

export type GraphQLContentfulQueryRichTextOnlyArgs = {
  id: Scalars["String"];
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulQueryRichTextOnlyCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
  where?: Maybe<GraphQLContentfulRichTextOnlyFilter>;
  order?: Maybe<Array<Maybe<GraphQLContentfulRichTextOnlyOrder>>>;
};

export type GraphQLContentfulQueryResourcesAndContactsArgs = {
  id: Scalars["String"];
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulQueryResourcesAndContactsCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
  where?: Maybe<GraphQLContentfulResourcesAndContactsFilter>;
  order?: Maybe<Array<Maybe<GraphQLContentfulResourcesAndContactsOrder>>>;
};

export type GraphQLContentfulQueryOfferingExampleViolationArgs = {
  id: Scalars["String"];
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulQueryOfferingExampleViolationCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
  where?: Maybe<GraphQLContentfulOfferingExampleViolationFilter>;
  order?: Maybe<Array<Maybe<GraphQLContentfulOfferingExampleViolationOrder>>>;
};

export type GraphQLContentfulQueryLandingFactArgs = {
  id: Scalars["String"];
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulQueryLandingFactCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
  where?: Maybe<GraphQLContentfulLandingFactFilter>;
  order?: Maybe<Array<Maybe<GraphQLContentfulLandingFactOrder>>>;
};

export type GraphQLContentfulQueryLandingMetadataArgs = {
  id: Scalars["String"];
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulQueryLandingMetadataCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
  where?: Maybe<GraphQLContentfulLandingMetadataFilter>;
  order?: Maybe<Array<Maybe<GraphQLContentfulLandingMetadataOrder>>>;
};

export type GraphQLContentfulQueryRelevantArticleArgs = {
  id: Scalars["String"];
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulQueryRelevantArticleCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
  where?: Maybe<GraphQLContentfulRelevantArticleFilter>;
  order?: Maybe<Array<Maybe<GraphQLContentfulRelevantArticleOrder>>>;
};

export type GraphQLContentfulQueryDidYouKnowArgs = {
  id: Scalars["String"];
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulQueryDidYouKnowCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
  where?: Maybe<GraphQLContentfulDidYouKnowFilter>;
  order?: Maybe<Array<Maybe<GraphQLContentfulDidYouKnowOrder>>>;
};

export type GraphQLContentfulQueryLandingExplanationArgs = {
  id: Scalars["String"];
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulQueryLandingExplanationCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
  where?: Maybe<GraphQLContentfulLandingExplanationFilter>;
  order?: Maybe<Array<Maybe<GraphQLContentfulLandingExplanationOrder>>>;
};

export type GraphQLContentfulQueryEntryCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
  where?: Maybe<GraphQLContentfulEntryFilter>;
  order?: Maybe<Array<Maybe<GraphQLContentfulEntryOrder>>>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/relevantArticle) */
export type GraphQLContentfulRelevantArticle = GraphQLContentfulEntry & {
  __typename?: "RelevantArticle";
  sys: GraphQLContentfulSys;
  contentfulMetadata: GraphQLContentfulContentfulMetadata;
  linkedFrom?: Maybe<GraphQLContentfulRelevantArticleLinkingCollections>;
  title?: Maybe<Scalars["String"]>;
  sourceName?: Maybe<Scalars["String"]>;
  sourceUrl?: Maybe<Scalars["String"]>;
  order?: Maybe<Scalars["Int"]>;
  previewImage?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/relevantArticle) */
export type GraphQLContentfulRelevantArticleLinkedFromArgs = {
  allowedLocales?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/relevantArticle) */
export type GraphQLContentfulRelevantArticleTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/relevantArticle) */
export type GraphQLContentfulRelevantArticleSourceNameArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/relevantArticle) */
export type GraphQLContentfulRelevantArticleSourceUrlArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/relevantArticle) */
export type GraphQLContentfulRelevantArticleOrderArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/relevantArticle) */
export type GraphQLContentfulRelevantArticlePreviewImageArgs = {
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulRelevantArticleCollection = {
  __typename?: "RelevantArticleCollection";
  total: Scalars["Int"];
  skip: Scalars["Int"];
  limit: Scalars["Int"];
  items: Array<Maybe<GraphQLContentfulRelevantArticle>>;
};

export type GraphQLContentfulRelevantArticleFilter = {
  sys?: Maybe<GraphQLContentfulSysFilter>;
  contentfulMetadata?: Maybe<GraphQLContentfulContentfulMetadataFilter>;
  title_exists?: Maybe<Scalars["Boolean"]>;
  title?: Maybe<Scalars["String"]>;
  title_not?: Maybe<Scalars["String"]>;
  title_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_contains?: Maybe<Scalars["String"]>;
  title_not_contains?: Maybe<Scalars["String"]>;
  sourceName_exists?: Maybe<Scalars["Boolean"]>;
  sourceName?: Maybe<Scalars["String"]>;
  sourceName_not?: Maybe<Scalars["String"]>;
  sourceName_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  sourceName_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  sourceName_contains?: Maybe<Scalars["String"]>;
  sourceName_not_contains?: Maybe<Scalars["String"]>;
  sourceUrl_exists?: Maybe<Scalars["Boolean"]>;
  sourceUrl?: Maybe<Scalars["String"]>;
  sourceUrl_not?: Maybe<Scalars["String"]>;
  sourceUrl_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  sourceUrl_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  sourceUrl_contains?: Maybe<Scalars["String"]>;
  sourceUrl_not_contains?: Maybe<Scalars["String"]>;
  order_exists?: Maybe<Scalars["Boolean"]>;
  order?: Maybe<Scalars["Int"]>;
  order_not?: Maybe<Scalars["Int"]>;
  order_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_not_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_gt?: Maybe<Scalars["Int"]>;
  order_gte?: Maybe<Scalars["Int"]>;
  order_lt?: Maybe<Scalars["Int"]>;
  order_lte?: Maybe<Scalars["Int"]>;
  previewImage_exists?: Maybe<Scalars["Boolean"]>;
  previewImage?: Maybe<Scalars["String"]>;
  previewImage_not?: Maybe<Scalars["String"]>;
  previewImage_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  previewImage_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  previewImage_contains?: Maybe<Scalars["String"]>;
  previewImage_not_contains?: Maybe<Scalars["String"]>;
  OR?: Maybe<Array<Maybe<GraphQLContentfulRelevantArticleFilter>>>;
  AND?: Maybe<Array<Maybe<GraphQLContentfulRelevantArticleFilter>>>;
};

export type GraphQLContentfulRelevantArticleLinkingCollections = {
  __typename?: "RelevantArticleLinkingCollections";
  entryCollection?: Maybe<GraphQLContentfulEntryCollection>;
};

export type GraphQLContentfulRelevantArticleLinkingCollectionsEntryCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulRelevantArticleOrder =
  | "title_ASC"
  | "title_DESC"
  | "sourceName_ASC"
  | "sourceName_DESC"
  | "sourceUrl_ASC"
  | "sourceUrl_DESC"
  | "order_ASC"
  | "order_DESC"
  | "previewImage_ASC"
  | "previewImage_DESC"
  | "sys_id_ASC"
  | "sys_id_DESC"
  | "sys_publishedAt_ASC"
  | "sys_publishedAt_DESC"
  | "sys_firstPublishedAt_ASC"
  | "sys_firstPublishedAt_DESC"
  | "sys_publishedVersion_ASC"
  | "sys_publishedVersion_DESC";

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/resourcesAndContacts) */
export type GraphQLContentfulResourcesAndContacts = GraphQLContentfulEntry & {
  __typename?: "ResourcesAndContacts";
  sys: GraphQLContentfulSys;
  contentfulMetadata: GraphQLContentfulContentfulMetadata;
  linkedFrom?: Maybe<GraphQLContentfulResourcesAndContactsLinkingCollections>;
  name?: Maybe<Scalars["String"]>;
  nameUrl?: Maybe<Scalars["String"]>;
  description?: Maybe<GraphQLContentfulResourcesAndContactsDescription>;
  email?: Maybe<Scalars["String"]>;
  phoneNumber?: Maybe<Scalars["String"]>;
  phoneNumberExtension?: Maybe<Scalars["String"]>;
  facebookName?: Maybe<Scalars["String"]>;
  facebookUrl?: Maybe<Scalars["String"]>;
  order?: Maybe<Scalars["Int"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/resourcesAndContacts) */
export type GraphQLContentfulResourcesAndContactsLinkedFromArgs = {
  allowedLocales?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/resourcesAndContacts) */
export type GraphQLContentfulResourcesAndContactsNameArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/resourcesAndContacts) */
export type GraphQLContentfulResourcesAndContactsNameUrlArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/resourcesAndContacts) */
export type GraphQLContentfulResourcesAndContactsDescriptionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/resourcesAndContacts) */
export type GraphQLContentfulResourcesAndContactsEmailArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/resourcesAndContacts) */
export type GraphQLContentfulResourcesAndContactsPhoneNumberArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/resourcesAndContacts) */
export type GraphQLContentfulResourcesAndContactsPhoneNumberExtensionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/resourcesAndContacts) */
export type GraphQLContentfulResourcesAndContactsFacebookNameArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/resourcesAndContacts) */
export type GraphQLContentfulResourcesAndContactsFacebookUrlArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/resourcesAndContacts) */
export type GraphQLContentfulResourcesAndContactsOrderArgs = {
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulResourcesAndContactsCollection = {
  __typename?: "ResourcesAndContactsCollection";
  total: Scalars["Int"];
  skip: Scalars["Int"];
  limit: Scalars["Int"];
  items: Array<Maybe<GraphQLContentfulResourcesAndContacts>>;
};

export type GraphQLContentfulResourcesAndContactsDescription = {
  __typename?: "ResourcesAndContactsDescription";
  json: Scalars["JSON"];
  links: GraphQLContentfulResourcesAndContactsDescriptionLinks;
};

export type GraphQLContentfulResourcesAndContactsDescriptionAssets = {
  __typename?: "ResourcesAndContactsDescriptionAssets";
  hyperlink: Array<Maybe<GraphQLContentfulAsset>>;
  block: Array<Maybe<GraphQLContentfulAsset>>;
};

export type GraphQLContentfulResourcesAndContactsDescriptionEntries = {
  __typename?: "ResourcesAndContactsDescriptionEntries";
  inline: Array<Maybe<GraphQLContentfulEntry>>;
  hyperlink: Array<Maybe<GraphQLContentfulEntry>>;
  block: Array<Maybe<GraphQLContentfulEntry>>;
};

export type GraphQLContentfulResourcesAndContactsDescriptionLinks = {
  __typename?: "ResourcesAndContactsDescriptionLinks";
  entries: GraphQLContentfulResourcesAndContactsDescriptionEntries;
  assets: GraphQLContentfulResourcesAndContactsDescriptionAssets;
};

export type GraphQLContentfulResourcesAndContactsFilter = {
  sys?: Maybe<GraphQLContentfulSysFilter>;
  contentfulMetadata?: Maybe<GraphQLContentfulContentfulMetadataFilter>;
  name_exists?: Maybe<Scalars["Boolean"]>;
  name?: Maybe<Scalars["String"]>;
  name_not?: Maybe<Scalars["String"]>;
  name_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  name_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  name_contains?: Maybe<Scalars["String"]>;
  name_not_contains?: Maybe<Scalars["String"]>;
  nameUrl_exists?: Maybe<Scalars["Boolean"]>;
  nameUrl?: Maybe<Scalars["String"]>;
  nameUrl_not?: Maybe<Scalars["String"]>;
  nameUrl_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  nameUrl_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  nameUrl_contains?: Maybe<Scalars["String"]>;
  nameUrl_not_contains?: Maybe<Scalars["String"]>;
  description_exists?: Maybe<Scalars["Boolean"]>;
  description_contains?: Maybe<Scalars["String"]>;
  description_not_contains?: Maybe<Scalars["String"]>;
  email_exists?: Maybe<Scalars["Boolean"]>;
  email?: Maybe<Scalars["String"]>;
  email_not?: Maybe<Scalars["String"]>;
  email_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  email_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  email_contains?: Maybe<Scalars["String"]>;
  email_not_contains?: Maybe<Scalars["String"]>;
  phoneNumber_exists?: Maybe<Scalars["Boolean"]>;
  phoneNumber?: Maybe<Scalars["String"]>;
  phoneNumber_not?: Maybe<Scalars["String"]>;
  phoneNumber_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  phoneNumber_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  phoneNumber_contains?: Maybe<Scalars["String"]>;
  phoneNumber_not_contains?: Maybe<Scalars["String"]>;
  phoneNumberExtension_exists?: Maybe<Scalars["Boolean"]>;
  phoneNumberExtension?: Maybe<Scalars["String"]>;
  phoneNumberExtension_not?: Maybe<Scalars["String"]>;
  phoneNumberExtension_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  phoneNumberExtension_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  phoneNumberExtension_contains?: Maybe<Scalars["String"]>;
  phoneNumberExtension_not_contains?: Maybe<Scalars["String"]>;
  facebookName_exists?: Maybe<Scalars["Boolean"]>;
  facebookName?: Maybe<Scalars["String"]>;
  facebookName_not?: Maybe<Scalars["String"]>;
  facebookName_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  facebookName_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  facebookName_contains?: Maybe<Scalars["String"]>;
  facebookName_not_contains?: Maybe<Scalars["String"]>;
  facebookUrl_exists?: Maybe<Scalars["Boolean"]>;
  facebookUrl?: Maybe<Scalars["String"]>;
  facebookUrl_not?: Maybe<Scalars["String"]>;
  facebookUrl_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  facebookUrl_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  facebookUrl_contains?: Maybe<Scalars["String"]>;
  facebookUrl_not_contains?: Maybe<Scalars["String"]>;
  order_exists?: Maybe<Scalars["Boolean"]>;
  order?: Maybe<Scalars["Int"]>;
  order_not?: Maybe<Scalars["Int"]>;
  order_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_not_in?: Maybe<Array<Maybe<Scalars["Int"]>>>;
  order_gt?: Maybe<Scalars["Int"]>;
  order_gte?: Maybe<Scalars["Int"]>;
  order_lt?: Maybe<Scalars["Int"]>;
  order_lte?: Maybe<Scalars["Int"]>;
  OR?: Maybe<Array<Maybe<GraphQLContentfulResourcesAndContactsFilter>>>;
  AND?: Maybe<Array<Maybe<GraphQLContentfulResourcesAndContactsFilter>>>;
};

export type GraphQLContentfulResourcesAndContactsLinkingCollections = {
  __typename?: "ResourcesAndContactsLinkingCollections";
  entryCollection?: Maybe<GraphQLContentfulEntryCollection>;
};

export type GraphQLContentfulResourcesAndContactsLinkingCollectionsEntryCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulResourcesAndContactsOrder =
  | "name_ASC"
  | "name_DESC"
  | "nameUrl_ASC"
  | "nameUrl_DESC"
  | "email_ASC"
  | "email_DESC"
  | "phoneNumber_ASC"
  | "phoneNumber_DESC"
  | "phoneNumberExtension_ASC"
  | "phoneNumberExtension_DESC"
  | "facebookName_ASC"
  | "facebookName_DESC"
  | "facebookUrl_ASC"
  | "facebookUrl_DESC"
  | "order_ASC"
  | "order_DESC"
  | "sys_id_ASC"
  | "sys_id_DESC"
  | "sys_publishedAt_ASC"
  | "sys_publishedAt_DESC"
  | "sys_firstPublishedAt_ASC"
  | "sys_firstPublishedAt_DESC"
  | "sys_publishedVersion_ASC"
  | "sys_publishedVersion_DESC";

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/richTextOnly) */
export type GraphQLContentfulRichTextOnly = GraphQLContentfulEntry & {
  __typename?: "RichTextOnly";
  sys: GraphQLContentfulSys;
  contentfulMetadata: GraphQLContentfulContentfulMetadata;
  linkedFrom?: Maybe<GraphQLContentfulRichTextOnlyLinkingCollections>;
  title?: Maybe<Scalars["String"]>;
  path?: Maybe<Scalars["String"]>;
  description?: Maybe<GraphQLContentfulRichTextOnlyDescription>;
  seoDescription?: Maybe<Scalars["String"]>;
  showStartButton?: Maybe<Scalars["Boolean"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/richTextOnly) */
export type GraphQLContentfulRichTextOnlyLinkedFromArgs = {
  allowedLocales?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/richTextOnly) */
export type GraphQLContentfulRichTextOnlyTitleArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/richTextOnly) */
export type GraphQLContentfulRichTextOnlyPathArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/richTextOnly) */
export type GraphQLContentfulRichTextOnlyDescriptionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/richTextOnly) */
export type GraphQLContentfulRichTextOnlySeoDescriptionArgs = {
  locale?: Maybe<Scalars["String"]>;
};

/** [See type definition](https://app.contentful.com/spaces/56c95v53ajrr/content_types/richTextOnly) */
export type GraphQLContentfulRichTextOnlyShowStartButtonArgs = {
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulRichTextOnlyCollection = {
  __typename?: "RichTextOnlyCollection";
  total: Scalars["Int"];
  skip: Scalars["Int"];
  limit: Scalars["Int"];
  items: Array<Maybe<GraphQLContentfulRichTextOnly>>;
};

export type GraphQLContentfulRichTextOnlyDescription = {
  __typename?: "RichTextOnlyDescription";
  json: Scalars["JSON"];
  links: GraphQLContentfulRichTextOnlyDescriptionLinks;
};

export type GraphQLContentfulRichTextOnlyDescriptionAssets = {
  __typename?: "RichTextOnlyDescriptionAssets";
  hyperlink: Array<Maybe<GraphQLContentfulAsset>>;
  block: Array<Maybe<GraphQLContentfulAsset>>;
};

export type GraphQLContentfulRichTextOnlyDescriptionEntries = {
  __typename?: "RichTextOnlyDescriptionEntries";
  inline: Array<Maybe<GraphQLContentfulEntry>>;
  hyperlink: Array<Maybe<GraphQLContentfulEntry>>;
  block: Array<Maybe<GraphQLContentfulEntry>>;
};

export type GraphQLContentfulRichTextOnlyDescriptionLinks = {
  __typename?: "RichTextOnlyDescriptionLinks";
  entries: GraphQLContentfulRichTextOnlyDescriptionEntries;
  assets: GraphQLContentfulRichTextOnlyDescriptionAssets;
};

export type GraphQLContentfulRichTextOnlyFilter = {
  sys?: Maybe<GraphQLContentfulSysFilter>;
  contentfulMetadata?: Maybe<GraphQLContentfulContentfulMetadataFilter>;
  title_exists?: Maybe<Scalars["Boolean"]>;
  title?: Maybe<Scalars["String"]>;
  title_not?: Maybe<Scalars["String"]>;
  title_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  title_contains?: Maybe<Scalars["String"]>;
  title_not_contains?: Maybe<Scalars["String"]>;
  path_exists?: Maybe<Scalars["Boolean"]>;
  path?: Maybe<Scalars["String"]>;
  path_not?: Maybe<Scalars["String"]>;
  path_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  path_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  path_contains?: Maybe<Scalars["String"]>;
  path_not_contains?: Maybe<Scalars["String"]>;
  description_exists?: Maybe<Scalars["Boolean"]>;
  description_contains?: Maybe<Scalars["String"]>;
  description_not_contains?: Maybe<Scalars["String"]>;
  seoDescription_exists?: Maybe<Scalars["Boolean"]>;
  seoDescription?: Maybe<Scalars["String"]>;
  seoDescription_not?: Maybe<Scalars["String"]>;
  seoDescription_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  seoDescription_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  seoDescription_contains?: Maybe<Scalars["String"]>;
  seoDescription_not_contains?: Maybe<Scalars["String"]>;
  showStartButton_exists?: Maybe<Scalars["Boolean"]>;
  showStartButton?: Maybe<Scalars["Boolean"]>;
  showStartButton_not?: Maybe<Scalars["Boolean"]>;
  OR?: Maybe<Array<Maybe<GraphQLContentfulRichTextOnlyFilter>>>;
  AND?: Maybe<Array<Maybe<GraphQLContentfulRichTextOnlyFilter>>>;
};

export type GraphQLContentfulRichTextOnlyLinkingCollections = {
  __typename?: "RichTextOnlyLinkingCollections";
  entryCollection?: Maybe<GraphQLContentfulEntryCollection>;
};

export type GraphQLContentfulRichTextOnlyLinkingCollectionsEntryCollectionArgs = {
  skip?: Maybe<Scalars["Int"]>;
  limit?: Maybe<Scalars["Int"]>;
  preview?: Maybe<Scalars["Boolean"]>;
  locale?: Maybe<Scalars["String"]>;
};

export type GraphQLContentfulRichTextOnlyOrder =
  | "title_ASC"
  | "title_DESC"
  | "path_ASC"
  | "path_DESC"
  | "showStartButton_ASC"
  | "showStartButton_DESC"
  | "sys_id_ASC"
  | "sys_id_DESC"
  | "sys_publishedAt_ASC"
  | "sys_publishedAt_DESC"
  | "sys_firstPublishedAt_ASC"
  | "sys_firstPublishedAt_DESC"
  | "sys_publishedVersion_ASC"
  | "sys_publishedVersion_DESC";

export type GraphQLContentfulSys = {
  __typename?: "Sys";
  id: Scalars["String"];
  spaceId: Scalars["String"];
  environmentId: Scalars["String"];
  publishedAt?: Maybe<Scalars["DateTime"]>;
  firstPublishedAt?: Maybe<Scalars["DateTime"]>;
  publishedVersion?: Maybe<Scalars["Int"]>;
};

export type GraphQLContentfulSysFilter = {
  id_exists?: Maybe<Scalars["Boolean"]>;
  id?: Maybe<Scalars["String"]>;
  id_not?: Maybe<Scalars["String"]>;
  id_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  id_not_in?: Maybe<Array<Maybe<Scalars["String"]>>>;
  id_contains?: Maybe<Scalars["String"]>;
  id_not_contains?: Maybe<Scalars["String"]>;
  publishedAt_exists?: Maybe<Scalars["Boolean"]>;
  publishedAt?: Maybe<Scalars["DateTime"]>;
  publishedAt_not?: Maybe<Scalars["DateTime"]>;
  publishedAt_in?: Maybe<Array<Maybe<Scalars["DateTime"]>>>;
  publishedAt_not_in?: Maybe<Array<Maybe<Scalars["DateTime"]>>>;
  publishedAt_gt?: Maybe<Scalars["DateTime"]>;
  publishedAt_gte?: Maybe<Scalars["DateTime"]>;
  publishedAt_lt?: Maybe<Scalars["DateTime"]>;
  publishedAt_lte?: Maybe<Scalars["DateTime"]>;
  firstPublishedAt_exists?: Maybe<Scalars["Boolean"]>;
  firstPublishedAt?: Maybe<Scalars["DateTime"]>;
  firstPublishedAt_not?: Maybe<Scalars["DateTime"]>;
  firstPublishedAt_in?: Maybe<Array<Maybe<Scalars["DateTime"]>>>;
  firstPublishedAt_not_in?: Maybe<Array<Maybe<Scalars["DateTime"]>>>;
  firstPublishedAt_gt?: Maybe<Scalars["DateTime"]>;
  firstPublishedAt_gte?: Maybe<Scalars["DateTime"]>;
  firstPublishedAt_lt?: Maybe<Scalars["DateTime"]>;
  firstPublishedAt_lte?: Maybe<Scalars["DateTime"]>;
  publishedVersion_exists?: Maybe<Scalars["Boolean"]>;
  publishedVersion?: Maybe<Scalars["Float"]>;
  publishedVersion_not?: Maybe<Scalars["Float"]>;
  publishedVersion_in?: Maybe<Array<Maybe<Scalars["Float"]>>>;
  publishedVersion_not_in?: Maybe<Array<Maybe<Scalars["Float"]>>>;
  publishedVersion_gt?: Maybe<Scalars["Float"]>;
  publishedVersion_gte?: Maybe<Scalars["Float"]>;
  publishedVersion_lt?: Maybe<Scalars["Float"]>;
  publishedVersion_lte?: Maybe<Scalars["Float"]>;
};

export type GraphQLContentfulAllBlogPostsQueryVariables = Exact<{
  [key: string]: never;
}>;

export type GraphQLContentfulAllBlogPostsQuery = { __typename?: "Query" } & {
  blogPostCollection?: Maybe<
    { __typename?: "BlogPostCollection" } & {
      items: Array<
        Maybe<
          { __typename: "BlogPost" } & Pick<GraphQLContentfulBlogPost, "path">
        >
      >;
    }
  >;
};

export type GraphQLContentfulBlogPostPageQueryVariables = Exact<{
  [key: string]: never;
}>;

export type GraphQLContentfulBlogPostPageQuery = { __typename?: "Query" } & {
  pinnedPosts?: Maybe<
    { __typename?: "BlogPostCollection" } & {
      items: Array<
        Maybe<
          { __typename?: "BlogPost" } & Pick<
            GraphQLContentfulBlogPost,
            | "title"
            | "path"
            | "author"
            | "tags"
            | "externalUrl"
            | "seoDescription"
          > & {
              image?: Maybe<
                { __typename?: "Asset" } & Pick<
                  GraphQLContentfulAsset,
                  "url" | "description"
                >
              >;
              richDescription?: Maybe<
                { __typename?: "BlogPostDescription" } & Pick<
                  GraphQLContentfulBlogPostDescription,
                  "json"
                >
              >;
              sys: { __typename?: "Sys" } & Pick<
                GraphQLContentfulSys,
                "firstPublishedAt"
              >;
            }
        >
      >;
    }
  >;
  recentPosts?: Maybe<
    { __typename?: "BlogPostCollection" } & {
      items: Array<
        Maybe<
          { __typename?: "BlogPost" } & Pick<
            GraphQLContentfulBlogPost,
            | "title"
            | "path"
            | "author"
            | "tags"
            | "externalUrl"
            | "seoDescription"
          > & {
              image?: Maybe<
                { __typename?: "Asset" } & Pick<
                  GraphQLContentfulAsset,
                  "url" | "description"
                >
              >;
              richDescription?: Maybe<
                { __typename?: "BlogPostDescription" } & Pick<
                  GraphQLContentfulBlogPostDescription,
                  "json"
                >
              >;
              sys: { __typename?: "Sys" } & Pick<
                GraphQLContentfulSys,
                "firstPublishedAt"
              >;
            }
        >
      >;
    }
  >;
};

export type GraphQLContentfulBlogPostFromPathQueryVariables = Exact<{
  path?: Maybe<Scalars["String"]>;
}>;

export type GraphQLContentfulBlogPostFromPathQuery = {
  __typename?: "Query";
} & {
  blogPostCollection?: Maybe<
    { __typename?: "BlogPostCollection" } & {
      items: Array<
        Maybe<
          { __typename?: "BlogPost" } & Pick<
            GraphQLContentfulBlogPost,
            | "title"
            | "path"
            | "author"
            | "tags"
            | "externalUrl"
            | "seoDescription"
          > & {
              image?: Maybe<
                { __typename?: "Asset" } & Pick<
                  GraphQLContentfulAsset,
                  "url" | "description"
                >
              >;
              richDescription?: Maybe<
                { __typename?: "BlogPostDescription" } & Pick<
                  GraphQLContentfulBlogPostDescription,
                  "json"
                >
              >;
              sys: { __typename?: "Sys" } & Pick<
                GraphQLContentfulSys,
                "firstPublishedAt"
              >;
            }
        >
      >;
    }
  >;
};

export type GraphQLContentfulLandingPageContentQueryVariables = Exact<{
  [key: string]: never;
}>;

export type GraphQLContentfulLandingPageContentQuery = {
  __typename?: "Query";
} & {
  entryCollection?: Maybe<
    { __typename?: "EntryCollection" } & {
      items: Array<
        Maybe<
          | { __typename: "BlogPost" }
          | ({ __typename: "DidYouKnow" } & Pick<
              GraphQLContentfulDidYouKnow,
              "title" | "description" | "sourceName" | "sourceUrl" | "order"
            >)
          | ({ __typename: "LandingExplanation" } & Pick<
              GraphQLContentfulLandingExplanation,
              "icon" | "order"
            > & {
                richDescription?: Maybe<
                  { __typename?: "LandingExplanationDescription" } & Pick<
                    GraphQLContentfulLandingExplanationDescription,
                    "json"
                  >
                >;
              })
          | ({ __typename: "LandingFact" } & Pick<
              GraphQLContentfulLandingFact,
              "title" | "description" | "order" | "lightTextColor"
            > & {
                backgroundImage?: Maybe<
                  { __typename?: "Asset" } & Pick<GraphQLContentfulAsset, "url">
                >;
              })
          | ({ __typename: "LandingMetadata" } & Pick<
              GraphQLContentfulLandingMetadata,
              | "title"
              | "buttonStartNow"
              | "whyThisToolTitle"
              | "howWeHelpTitle"
              | "didYouKnowTitle"
              | "kitchenIntro"
              | "articleTitle"
            > & {
                richDescription?: Maybe<
                  { __typename?: "LandingMetadataDescription" } & Pick<
                    GraphQLContentfulLandingMetadataDescription,
                    "json"
                  >
                >;
              })
          | ({ __typename: "OfferingExampleViolation" } & Pick<
              GraphQLContentfulOfferingExampleViolation,
              | "title"
              | "description"
              | "violationReason"
              | "order"
              | "markerLeftPosition"
              | "markerTopPosition"
            >)
          | ({ __typename: "RelevantArticle" } & Pick<
              GraphQLContentfulRelevantArticle,
              "title" | "sourceUrl" | "sourceName" | "order"
            >)
          | { __typename: "ResourcesAndContacts" }
          | { __typename: "RichTextOnly" }
        >
      >;
    }
  >;
};

export type GraphQLContentfulResourcesPageContentQueryVariables = Exact<{
  [key: string]: never;
}>;

export type GraphQLContentfulResourcesPageContentQuery = {
  __typename?: "Query";
} & {
  resourcesAndContactsCollection?: Maybe<
    { __typename?: "ResourcesAndContactsCollection" } & {
      items: Array<
        Maybe<
          { __typename: "ResourcesAndContacts" } & Pick<
            GraphQLContentfulResourcesAndContacts,
            | "name"
            | "nameUrl"
            | "email"
            | "phoneNumber"
            | "phoneNumberExtension"
            | "facebookName"
            | "facebookUrl"
            | "order"
          > & {
              richDescription?: Maybe<
                { __typename?: "ResourcesAndContactsDescription" } & Pick<
                  GraphQLContentfulResourcesAndContactsDescription,
                  "json"
                >
              >;
            }
        >
      >;
    }
  >;
};

export type GraphQLContentfulAllRichTextPagesQueryVariables = Exact<{
  [key: string]: never;
}>;

export type GraphQLContentfulAllRichTextPagesQuery = {
  __typename?: "Query";
} & {
  richTextOnlyCollection?: Maybe<
    { __typename?: "RichTextOnlyCollection" } & {
      items: Array<
        Maybe<
          { __typename: "RichTextOnly" } & Pick<
            GraphQLContentfulRichTextOnly,
            "path"
          >
        >
      >;
    }
  >;
};

export type GraphQLContentfulRichTextPageQueryVariables = Exact<{
  path?: Maybe<Scalars["String"]>;
}>;

export type GraphQLContentfulRichTextPageQuery = { __typename?: "Query" } & {
  richTextOnlyCollection?: Maybe<
    { __typename?: "RichTextOnlyCollection" } & {
      items: Array<
        Maybe<
          { __typename: "RichTextOnly" } & Pick<
            GraphQLContentfulRichTextOnly,
            "title" | "seoDescription" | "showStartButton"
          > & {
              richDescription?: Maybe<
                { __typename?: "RichTextOnlyDescription" } & Pick<
                  GraphQLContentfulRichTextOnlyDescription,
                  "json"
                >
              >;
            }
        >
      >;
    }
  >;
};
