name: unit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: "install dependencies"
        working-directory: ${{ env.working-directory }}
        run: npm install
      - name: "run unit"
        working-directory: ${{ env.working-directory }}
        run: "npm run unit"
